# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 08:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nazwa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_projektu', models.CharField(max_length=50)),
                ('krotki_opis', models.CharField(max_length=200)),
                ('dlugi_opis', models.CharField(max_length=500)),
                ('problemy', models.CharField(max_length=500)),
                ('bledy', models.CharField(max_length=500)),
                ('szkola', models.CharField(max_length=200)),
                ('liczba_uczniow', models.IntegerField(default=0)),
                ('informacje', models.CharField(max_length=200)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'nazwy',
            },
        ),
    ]
