# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-07 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projekty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nazwa',
            old_name='dlugi_projektu',
            new_name='dlugi_opis',
        ),
    ]
