# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projekty', '0002_remove_nazwa_data_publikacji'),
    ]

    operations = [
        migrations.AddField(
            model_name='nazwa',
            name='data_publikacji',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data publikacji'),
            preserve_default=False,
        ),
    ]
