# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 11:21
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekty', '0004_auto_20170413_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nazwa',
            name='zdjecie',
            field=models.FileField(upload_to=django.core.files.storage.FileSystemStorage(location='/media/photos')),
        ),
    ]
